name: Build

on:
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:
  
env:
  GH_ACTIONS: 'true'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '["**/README.md"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v2
    
    - uses: robinraju/release-downloader@v1.3
      with: 
        repository: " misternebula/quantum-space-buddies"
        latest: true
        fileName: "QSB.zip" # TODO: change this to Raicuparta.QuantumSpaceBuddies.zip on next release
        out-file-path: "QSB-Download/"
        
    - run: 7z x QSB-Download/QSB.zip # TODO: change this to Raicuparta.QuantumSpaceBuddies.zip on next release
    
    # Set to Release if we're in main, otherwise keep us in Debug
    - name: Set Release
      if: github.ref == 'refs/heads/main'
      run: echo "BUILD_TYPE=Release" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      
    - name: Set Debug
      if: github.ref != 'refs/heads/main'
      run: echo "BUILD_TYPE=Debug" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    
    - uses: actions/setup-dotnet@v1
      
    - run: dotnet build -c $Env:BUILD_TYPE -o .\NHQSBCompat\Bin\$Env:BUILD_TYPE
    - uses: actions/upload-artifact@v2
      with:
        name: NHQSBCompat-${{ env.BUILD_TYPE }}
        path: .\NHQSBCompat\Bin\${{ env.BUILD_TYPE }}